language: python
python:
  - "3.6"

cache:
  directories:
  - node_modules

before_install:
- wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
- nvm install 8
- node --version

before_script: 
  - pip install --user awscli
  - pip install --user aws-sam-cli
  - aws configure set region us-east-1
  - npm run copy-package
  - cd aws-api-gateway-developer-portal
  - npm run install
  - npm run package
  - npm run deploy
  - cd ..

script:
  #- cd aws-api-gateway-developer-portal
  - node ./scripts/getStackFeatures dev-portal #creates .env
  #- cp ./.env ../
  #- cd ..
  - wget -O releases.json https://api.github.com/repos/phillyfan1138/option_price_faas/releases/latest
  - echo "REACT_APP_TAG=$(node ./scripts/outputTag)" >> .env # creates tag for the main site to know which docs to grab
  - echo "SKIP_PREFLIGHT_CHECK=true" >> .env # skips check for module interactions
  - cd main_site
  - npm install
  - npm test -- --coverage
  - npm run build
  - wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalculation.pdf;
  - wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalibration.pdf;
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: ##Github token for pushing to pages
      secure: dbSsXp7XBdsrBbW5XtZyyC7fDzFjO2tnUBgpdj7LnML4BmcdPpNWTQ7pEDNU0P0fcQaOc3/NAE7YwDi71uKclo0bZyXfmlzgVOKTkFAuMwrkYMhvM29d2p919ezUVAnfvDSK7U2uT8wucC09sVGbMfdiCC+ep12/O5+3rMfGyeB8A8dIkXx0UwqErqyc8yyxm8S9orpHYGgspDtWUJuEkhUZ3SFQZuwTTKqA79h9b7KaP0/8nMOk8FW1Ck/zzw1fJNy9478EXLYfL8UiAybr1n1eRqWft4o/qHTC2KI9AG2+EvG3XCe/3WLyzWOgH0lst515g6nZybM/eZgxngvQj6egEVUd1GLFaWgC69BksfMvdfr9nd70kfgVqfYiEcCQU1TtSxR1htDphtCs7QDLb0bSLCykHYe6VR0DrE8EZxrmA15WY0/Fbi3DgA46rEP5s0K79NkvuxElC+JhHpMh+ygi36jabBFDr64as/ToVf604iVZiaMddWIi6FIgkdg65JXl7/f2QCUwy2iuxk+gVl7FWtteti++2seyM2xfgyTgxkVrDVQ0L8uN3snkuZkADEJgRGtBe8SyZa90hNs+VNjGUh7Kb9CEJPmmUjSmyXAnrlhW2rKlxbJqoIuaxfoh/XJO4Ma9CWqvZlzTsYwoeW7jjM8aWmIWhCjAAX0juvk=
    local_dir: build
    on:
      repo: realoptions/main_site
      branch: master
