language: python
python:
  - "3.6"

cache:
  directories:
  - node_modules

before_install:
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - nvm install 8
  - node --version

before_script: 
  - pip install awscli
  - aws configure set region us-east-1

script:
  - npm install
  - url=$(node ./scripts/getApiUrl)
  - googleClientId=$(node ./scripts/getGoogleId)
  - facebookAppId=$(node ./scripts/getFacebookId)
  - echo "REACT_APP_ApiUrl=$url" >.env
  - echo "REACT_APP_GoogleClientID=$googleClientId" >> .env
  - echo "REACT_APP_FacebookAppID=$facebookAppId" >> .env
  - cat .env
  - npm test -- --coverage
  - npm run build
  - cd build
  - wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalculation.pdf
  - wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalibration.pdf
  - cd ..
  - cd lambdas
  - echo "{\"GoogleClientID\":\"$googleClientId\", \"FacebookAppID\":\"$facebookAppId\"}" > clientInfo.json
  - npm install --only=prod
  - 

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - npm install -g serverless
  - sls deploy

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
      repo: realoptions/main_site
      branch: master