language: python
python:
  - "3.6"

cache:
  directories:
  - node_modules

before_install:
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - nvm install 8
  - node --version

before_script: 
  - pip install awscli
  - aws configure set region us-east-1

script:
  - npm ci
  - url=$(node ./scripts/getApiUrl)
  - googleClientId=$(node ./scripts/getGoogleId)
  - facebookAppId=$(node ./scripts/getFacebookId)
  - echo "REACT_APP_ApiUrl=$url" >.env
  - echo "REACT_APP_GoogleClientID=$googleClientId" >> .env
  - echo "REACT_APP_FacebookAppID=$facebookAppId" >> .env
  - for i in {1..5}; do wget -O ./scripts/releases.json https://api.github.com/repos/realoptions/option_price_faas/releases/latest?access_token=$GITHUB_TOKEN && break || sleep 10; done 
  - tag=$(node ./scripts/outputTag) # if this errors, it will throw and stop the build
  - echo "REACT_APP_TAG=$tag" >> .env
  - cat .env
  - npm test -- --coverage
  - npm run build
  - cd build
  - wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalculation.pdf
  - wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalibration.pdf
  - cd ..
  - cd lambdas
  - echo "{\"GoogleClientID\":\"$googleClientId\", \"FacebookAppID\":\"$facebookAppId\"}" > clientInfo.json
  - npm ci #to install dev dependencies includes jest
  - npm test 
  - rm -r node_modules #to uninstall dev dependencies for smaller lambda
  - npm ci --only=production #does not includes jest
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - npm install -g serverless
  - sls deploy

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
      repo: realoptions/main_site
      branch: master