language: node_js
node_js:
  - "8.10"

script:
  - npm install
  - url=$(node ./scripts/getApiUrl)
  - echo "REACT_APP_ApiUrl=$url" >.env
  - cat .env
  - npm test -- --coverage
  - npm run build
  - cd build
  - wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalculation.pdf
  - wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalibration.pdf
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - npm install -g serverless
  - sls deploy

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
      repo: realoptions/main_site
      branch: master