export const UPDATE_API_KEY = 'UPDATE_API_KEY'
export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE'
export const UPDATE_USAGE_PLAN = 'UPDATE_USAGE_PLAN'
