name: deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '23.5.0'
      - name: test
        run: |
          npm ci 
          npm test
        env:
          CI: true
      - name: setup for deploy
        run: |
          npm ci
          npm run build
          cd build
          cd ..
        env:
          CI: true

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy ghpages
        id: deployment
        uses: actions/deploy-pages@v4 