name: deploy
on:
    push:
      branches:
        - master
    repository_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: test
              run: |
                npm ci 
                npm test
              env:
                CI: true
            - name: setup for deploy
              run: |
                npm ci
                npm run build
                cd build
                wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalculation.pdf
                wget https://github.com/phillyfan1138/fang_oost_cal_charts/raw/master/docs/OptionCalibration.pdf
                cd ..
              env:
                CI: true
            
            - name: deploy ghpages
              uses: JamesIves/github-pages-deploy-action@master
              env: 
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                BRANCH: gh-pages
                FOLDER: build