name: test
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: test coverage
              run: |
                npm ci 
                npm test -- --coverage
                cd lambdas
                npm ci
                npm test -- --coverage
                cd ..
                bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
              env:
                CI: true